services:
    voicevox:
        image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
        ports:
            - "50021:50021"
        restart: unless-stopped

    ngrok:
        image: ngrok/ngrok:latest
        restart: unless-stopped
        command:
          - "start"
          - "--all"
          - "--config"
          - "/etc/ngrok.yml"
        volumes:
          - ./ngrok.yml:/etc/ngrok.yml
        ports:
          - 4040:4040
